profile: this is config-client 1.1.0-----0.0.1------123123123
content: chinese
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/solr_test
    password: root
    username: root
